# _config.yml
title: Journey to the Web 3
repository: mahpah/web3
# Generate permalinks in format specified in: https://jekyllrb.com/docs/permalinks/#built-in-formats
permalink: /:title/
kramdown:
  parse_block_html: true